# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [324]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [325]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [326]:
type(my_numpy_array)

numpy.ndarray

In [327]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [328]:
mini_matrix = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
mini_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [329]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.25606679, 0.34848597, 0.80929117, 0.49547733, 0.01899608,
       0.99878004, 0.71616539, 0.95200779, 0.83399933, 0.61641409,
       0.24979869, 0.88714428, 0.27481494, 0.72074018, 0.59814553,
       0.65415724, 0.53878557, 0.69612707, 0.58447462, 0.53579879])

In [330]:
# you can create a matrix of random number as well
x = np.random.rand(3, 3)
x

array([[0.50003593, 0.37906254, 0.69991461],
       [0.55108894, 0.32690922, 0.22617684],
       [0.82999851, 0.53657714, 0.56830718]])

In [331]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

47

In [332]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([60, 53, 18, 75, 65, 83, 95, 20, 89, 43, 59, 33, 85, 99, 33])

In [333]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [334]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [335]:
# Matrix of ones
x = np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [336]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [337]:
x = int(input('input a positive integer: '))

input a positive integer: 15


In [338]:
np_array = np.random.randint(1, x, 10)
np_array

array([ 6,  6, 13, 14,  4,  2,  6,  3,  8, 14])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [339]:
# np.arange() returns an evenly spaced values within a given interval
x= np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [340]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [341]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [342]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [343]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [344]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [345]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])

result = np.sqrt(X**2 + Y**2)
result

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [346]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20 ,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [347]:
# Access specific index from the numpy array
my_numpy_array[-1]

50

In [348]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3]

array([3, 5, 6])

In [349]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array_copy = my_numpy_array
my_numpy_array_copy[0:4] = 7
my_numpy_array_copy

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [350]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4,4))
matrix

array([[2, 8, 8, 5],
       [6, 2, 9, 7],
       [9, 7, 2, 5],
       [7, 6, 9, 3]])

In [351]:
# Get a row from a mtrix
matrix[-1]

array([7, 6, 9, 3])

In [352]:
# Get one element
matrix[-2][-1]

5

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [353]:
X = np.array([[2, 30, 20, -2, -4], [3, 4, 40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24 ,22 ,32 ,37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [354]:
X[-1] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [355]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[5, 3, 2, 8, 7],
       [2, 4, 4, 4, 6],
       [9, 4, 9, 2, 1],
       [1, 5, 6, 9, 6],
       [4, 9, 1, 3, 3]])

In [356]:
new_matrix = matrix[matrix > 7]
new_matrix

array([8, 9, 9, 9, 9])

In [357]:
# Obtain odd elements only
new_matrix = matrix[matrix % 2 != 0]
new_matrix

array([5, 3, 7, 9, 9, 1, 1, 5, 9, 9, 1, 3, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [358]:
X = np.array([[2, 30, 20, -2, -4],
             [3, 4, 40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [359]:
X[X < 0] = 0
X[X % 2 != 0] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [360]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [361]:
import pandas as pd

In [362]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [363]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [364]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [365]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [366]:
portfolio_df = pd.DataFrame({'stock ticker symbol':['ANZ', 'ORG', 'SCG'],
                             'number of shares':[3500, 5000, 4200],
                             'price per share':[24.13, 8.53, 2.52]})
portfolio_df

stock ticker symbol  number of shares  price per share
0                 ANZ              3500            24.13
1                 ORG              5000             8.53
2                 SCG              4200             2.52

In [367]:
stocks_value = portfolio_df['price per share'] * portfolio_df['number of shares']
stocks_value

0    84455.0
1    42650.0
2    10584.0
dtype: float64

In [368]:
stocks_value.sum()

137689.0

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [369]:
# Pandas is used to read a csv file and store data in a DataFrame

# Disable SSL verification
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [370]:
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [371]:
# Read tabular data using read_html
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [372]:
us_retirement_data = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')

In [373]:
us_retirement_data[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [374]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net Worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [375]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with bank'] >= 5]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [376]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [377]:
df_rich = bank_client_df[bank_client_df['Net Worth [$]'] >= 5000]
df_rich

Bank Client Name  Net Worth [$]  Years with bank
1            Steve          29000                4
2            Mitch          10000                9

In [378]:
df_rich['Net Worth [$]'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [379]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [380]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 

def networth_update(balance):
    return balance * 1.2


In [381]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [382]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [383]:
def new_stocks_price(stock_price):
 return (stock_price * 3) + 200

In [384]:
result = bank_client_df['Net worth [$]'].apply(new_stocks_price)
result

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [385]:
result.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [386]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [387]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank', inplace=False)

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [388]:
# Set inplace = True to ensure that change has taken place in memory

bank_client_df.sort_values(by = 'Years with bank', inplace=True)

In [389]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [390]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [391]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']}, 
                  index = [0, 1, 2, 3])

In [392]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [393]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index = [4, 5, 6, 7])

In [394]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [395]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index = [8, 9, 10, 11])

In [396]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [397]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [398]:
dataset = {'Bank Client ID': ['1', '2', '3', '4', '5'],
           'First Name': ['Patrick', 'John', 'Wayne', 'Cristiano', 'Luke'],
           'Last Name': ['Prayoonpruk', 'Cena', 'Rooney', 'Ronaldo', 'Shaw']}

In [399]:
Bank_df_1 = pd.DataFrame(dataset)
Bank_df_1

Bank Client ID First Name    Last Name
0              1    Patrick  Prayoonpruk
1              2       John         Cena
2              3      Wayne       Rooney
3              4  Cristiano      Ronaldo
4              5       Luke         Shaw

In [400]:
dataset_2 = {'Bank Client ID': ['6', '7', '8', '9', '10'],
             'First Name': ['David', 'Macus', 'Erling', 'Kevin', 'Jack'],
             'Last Name': ['De Gea', 'RashFord', 'Haaland', 'De Bruyne', 'Grealish']}


In [401]:
Bank_df_2 = pd.DataFrame(dataset_2)
Bank_df_2

Bank Client ID First Name  Last Name
0              6      David     De Gea
1              7      Macus   RashFord
2              8     Erling    Haaland
3              9      Kevin  De Bruyne
4             10       Jack   Grealish

In [402]:
dataset_sal = {'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
            'Annual Salary [$/year]': [300000, 500000, 1000000, 9999999, 800000, 650000, 600000, 550000, 5450000, 4750000]}

In [403]:
bank_df_sal = pd.DataFrame(dataset_sal, columns = ['Bank Client ID', 'Annual Salary [$/year]'])
bank_df_sal

Bank Client ID  Annual Salary [$/year]
0              1                  300000
1              2                  500000
2              3                 1000000
3              4                 9999999
4              5                  800000
5              6                  650000
6              7                  600000
7              8                  550000
8              9                 5450000
9             10                 4750000

In [404]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])

In [405]:
bank_df_all = pd.merge(bank_df_all, bank_df_sal, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name    Last Name  Annual Salary [$/year]
0              1    Patrick  Prayoonpruk                  300000
1              2       John         Cena                  500000
2              3      Wayne       Rooney                 1000000
3              4  Cristiano      Ronaldo                 9999999
4              5       Luke         Shaw                  800000
5              6      David       De Gea                  650000
6              7      Macus     RashFord                  600000
7              8     Erling      Haaland                  550000
8              9      Kevin    De Bruyne                 5450000
9             10       Jack     Grealish                 4750000

In [406]:
new_data = {'Bank Client ID': [11],
            'First Name': 'Methee',
            'Last Name': 'Heephong',
            'Annual Salary [$/year]': 10}

In [407]:
new_df = pd.DataFrame(new_data, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0              11     Methee  Heephong                      10

In [408]:
bank_df_all = pd.concat([bank_df_all, new_df])
bank_df_all

Bank Client ID First Name    Last Name  Annual Salary [$/year]
0              1    Patrick  Prayoonpruk                  300000
1              2       John         Cena                  500000
2              3      Wayne       Rooney                 1000000
3              4  Cristiano      Ronaldo                 9999999
4              5       Luke         Shaw                  800000
5              6      David       De Gea                  650000
6              7      Macus     RashFord                  600000
7              8     Erling      Haaland                  550000
8              9      Kevin    De Bruyne                 5450000
9             10       Jack     Grealish                 4750000
0             11     Methee     Heephong                      10

In [412]:
bank_df_all.columns

Index(['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'], dtype='object')